# Generated by Django 6.0.5 on 2026-06-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(choices=[('Elevation Design', 'Elevation Design'), ('Residential Houses', 'Residential Houses'), ('Residential Villas', 'Residential Villas'), ('Interior Design', 'Interior Design'), ('Landscape Design', 'Landscape Design'), ('Commercial Buildings', 'Commercial Buildings'), ('Renovation & Remodeling', 'Renovation & Remodeling')], default='Residential Villas', max_length=50),
        ),
    ]
